#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap.
# Disabled due to lack of reliance on Xmodmap.
# xmodmap "~/.Xmodmap"

# Start xfce-polkit authenticator

/usr/lib/xfce-polkit/xfce-polkit &

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
nm-applet &
xfce4-notifyd &
cbatticon &
volumeicon &
xfsettingsd &

# Set wallpaper

~/.fehbg &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
